### ISSUE TITLE
Docker container broken by new launch script.

### ISSUE THREAD

**Issue by mzr** [cahirwpz/mimiker#523]
Inside docker container we lack `libtmux`. In order to install it I had to also install `setuptools` package.
When i try to `./launch` mimiker I get:
```
Traceback (most recent call last):
  File "./launch", line 106, in <module>
    DevelRun(sim, dbg, uarts)
  File "./launch", line 40, in DevelRun
    window_name=':0', window_command='sleep 1')
  File "/home/mimiker/.local/lib/python3.5/site-packages/libtmux/server.py", line 511, in new_session
    session = Session(server=self, **session)
  File "/home/mimiker/.local/lib/python3.5/site-packages/libtmux/session.py", line 42, in __init__
    raise ValueError('Session requires a `session_id`')
ValueError: Session requires a `session_id`
```

**Comment by cahirwpz** [comment]
Please invoke `pip3 install libtmux` inside developer's Docker image.

**Comment by cahirwpz** [comment]
Docker image for developers is considered broken. There was noone interested in maintaining it. Hence it was removed. Good riddance!
