### ISSUE TITLE
run_tests.py does not properly report kernel timeouts

### ISSUE THREAD

**Issue by jpszczolowski** [cahirwpz/mimiker#686]
`run_tests.py` script launches kernel tests and waits until it sees `[TEST PASSED]` or `[TEST FAILED]` string. If there is a panic outside of a particular test function (e.g. during kernel startup), `run_tests.py` timeouts and fails to properly report the bug (please see an example below, in which I've added `assert(0)` to `atkbdc_probe` function).

This probably happens since https://github.com/cahirwpz/mimiker/commit/b63d0a2772fcaf726da017909f038be24daf5892, a change which increased `TIMEOUT` value from 20 to 40 (because the kernel with KASAN is ~2x slower).

```
$ ./run_tests.py
Testing seed 0...
Timeout reached.

qemu-mimiker-mipsel: -serial tcp:127.0.0.1:24031,server,wait: info: QEMU waiting for connection on: disconnected:tcp:127.0.0.1:24031,server
qemu-mimiker-mipsel: -serial tcp:127.0.0.1:24032,server,wait: info: QEMU waiting for connection on: disconnected:tcp:127.0.0.1:24032,server
qemu-mimiker-mipsel: -serial tcp:127.0.0.1:24033,server,wait: info: QEMU waiting for connection on: disconnected:tcp:127.0.0.1:24033,server
[pci:00:00.00] Bridge Device Marvell Technology Group Ltd. GT-64120/64120A/64121A System Controller
[pci:00:00.00] Interrupt: pin A routed to IRQ 0
[...]
Assertion "0" at [/home/jpszczolowski/mim2/sys/drv/atkbdc.c:123] failed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/pty_spawn.py", line 509, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_tests.py", line 136, in <module>
    test_seed(0, interactive)
  File "./run_tests.py", line 107, in test_seed
    gdb_inspect(interactive)
  File "./run_tests.py", line 47, in gdb_inspect
    send_command(gdb, 'backtrace full')
  File "./run_tests.py", line 24, in send_command
    gdb.expect_exact(['(gdb)'], timeout=10)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 418, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
```

Note: reporting bugs that happen during tests (so `ktest_failure` is called) works fine.

**Comment by cahirwpz** [comment]
Fixed by https://github.com/cahirwpz/mimiker/commit/946bc3bd53747e457d6608683b933deda245dd49
